#include <iostream>
#include <sstream>
using namespace std;

#include "tinyxml.h"
const char *demoQuiz =
    "<Quiz>\n"
        "<AllowedAttempts>1</AllowedAttempts>\n"
        "<ScoreLowered>0.30</ScoreLowered>\n"
        "<StudentName></StudentName>\n"
        "<Question>\n"
            "<QText>Where is called the 'Rooftop of the world'?</QText>\n"
            "<Choice item=1>Tibet</Choice>\n"
            "<Choice item=2>Sears Tower</Choice>\n"
            "<Choice item=3>Mt. McKinley</Choice>\n"
            "<Choice item=4>Nepal</Choice>\n"
            "<Answer>1</Answer>\n"
            "<Score>10</Score>\n"
        "</Question>\n"
        "<Question>\n"
            "<QText>Where is the 'Holy Land'?</QText>\n"
            "<Choice item=1>Jerusalem</Choice>\n"
            "<Choice item=2>Mathura</Choice>\n"
            "<Choice item=3>Mecca</Choice>\n"
            "<Choice item=4>Newark</Choice>\n"
            "<Answer>1</Answer>\n"
            "<Score>10</Score>\n"
        "</Question>\n"
         "<Question>\n"
            "<QText>Where is called 'The land of the rising sun'?</QText>\n"
            "<Choice item=1>Chicago</Choice>\n"
            "<Choice item=2>Japan</Choice>\n"
            "<Choice item=3>Tibet</Choice>\n"
            "<Choice item=4>Puerto Rico</Choice>\n"
            "<Answer>2</Answer>\n"
            "<Score>10</Score>\n"
        "</Question>\n"
                "<Question>\n"
            "<QText>What is called 'The gift of the Nile'?</QText>\n"
            "<Choice item=1>Chicago</Choice>\n"
            "<Choice item=2>Egypt</Choice>\n"
            "<Choice item=3>Africa</Choice>\n"
            "<Choice item=4>Alexandria</Choice>\n"
            "<Answer>2</Answer>\n"
            "<Score>10</Score>\n"
        "</Question>\n"
                "<Question>\n"
            "<QText>Where is the 'Land of Midnight'?</QText>\n"
            "<Choice item=1>Norway</Choice>\n"
            "<Choice item=2>Japan</Choice>\n"
            "<Choice item=3>Australia</Choice>\n"
            "<Choice item=4>Antartica</Choice>\n"
            "<Answer>1</Answer>\n"
            "<Score>10</Score>\n"
        "</Question>\n"
         "<Question>\n"
            "<QText>What is called 'The land of Thunderbolt?</QText>\n"
            "<Choice item=1>Wyomming</Choice>\n"
            "<Choice item=2>Canada</Choice>\n"
            "<Choice item=3>Arabia</Choice>\n"
            "<Choice item=4>Bhutan</Choice>\n"
            "<Answer>4</Answer>\n"
            "<Score>10</Score>\n"
        "</Question>\n"
         "<Question>\n"
            "<QText>Where is the 'Windy City'?</QText>\n"
            "<Choice item=1>Tokoyo</Choice>\n"
            "<Choice item=2>Taipai</Choice>\n"
            "<Choice item=3>Chicago</Choice>\n"
            "<Choice item=4>St Johns</Choice>\n"
            "<Answer>3</Answer>\n"
            "<Score>10</Score>\n"
        "</Question>\n"
         "<Question>\n"
            "<QText>Where is the 'Land of White Elephants'?</QText>\n"
            "<Choice item=1>Bangladesh</Choice>\n"
            "<Choice item=2>Thailand</Choice>\n"
            "<Choice item=3>India</Choice>\n"
            "<Choice item=4>South Africa</Choice>\n"
            "<Answer>2</Answer>\n"
            "<Score>10</Score>\n"
        "</Question>\n"
         "<Question>\n"
            "<QText>Where is the 'City of Seven Hills'?</QText>\n"
            "<Choice item=1>Rome</Choice>\n"
            "<Choice item=2>Nilgiri Hills</Choice>\n"
            "<Choice item=3>Tibet</Choice>\n"
            "<Choice item=4>Pittsburgh</Choice>\n"
            "<Answer>3</Answer>\n"
            "<Score>10</Score>\n"
        "</Question>\n"
         "<Question>\n"
            "<QText>What is called 'The Dark Contenient'?</QText>\n"
            "<Choice item=1>Asia</Choice>\n"
            "<Choice item=2>Australia</Choice>\n"
            "<Choice item=3>Africa</Choice>\n"
            "<Choice item=4>South America</Choice>\n"
            "<Score>10</Score>\n"
        "</Question>\n"
    "</Quiz>";

// Quick way to make demo file if needed
void demoQuizSave(){
    TiXmlDocument doc("quizinfo.xml");
    doc.Parse(demoQuiz);
    if (doc.Error()){
        cout << "Error in "<< doc.Value() <<": "<< doc.ErrorDesc()<< endl;
        exit(1);
    }
    doc.SaveFile();
}
int main(){
   demoQuizSave();
   return 0;
}